Repository DaoCloud/dce-charts-repackage, pull requests merged in 2022-12, with the labels that each got.

#313 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  contour-9.1.6.tgz
  coredns-metrics-0.1.0.tgz
  f5networks-0.2.0.tgz
  falco-2.0.17.tgz
  falco-event-generator-0.1.1.tgz
  falco-exporter-0.8.2.tgz
  index.yaml
  ingress-nginx-4.2.1.tgz
  metallb-0.13.5.tgz
  multus-underlay-0.1.6.tgz
  nmstate-0.74.0.tgz
  node-problem-detector-2.3.1.tgz
  spiderdoctor-0.2.7.tgz
  spiderpool-0.3.5.tgz
Labels: pr/release/robot_update_githubpage

#320 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  contour-9.1.6.tgz
  coredns-metrics-0.1.0.tgz
  f5networks-0.2.0.tgz
  falco-2.0.17.tgz
  falco-event-generator-0.1.1.tgz
  falco-exporter-0.8.2.tgz
  index.yaml
  ingress-nginx-4.2.1.tgz
  metallb-0.13.7.tgz
  multus-underlay-0.1.6.tgz
  nmstate-0.74.0.tgz
  node-problem-detector-2.3.1.tgz
  spiderdoctor-0.2.7.tgz
  spiderpool-0.3.5.tgz
Labels: pr/release/robot_update_githubpage

#328 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  contour-9.1.6.tgz
  coredns-metrics-0.1.0.tgz
  f5networks-0.2.0.tgz
  falco-2.0.17.tgz
  falco-event-generator-0.1.1.tgz
  falco-exporter-0.8.2.tgz
  index.yaml
  ingress-nginx-4.2.1.tgz
  metallb-0.13.7.tgz
  metrics-server-3.8.3.tgz
  multus-underlay-0.1.6.tgz
  nmstate-0.74.0.tgz
  node-problem-detector-2.3.1.tgz
  spiderdoctor-0.2.7.tgz
  spiderpool-0.3.5.tgz
  vpa-1.5.0.tgz
Labels: pr/release/robot_update_githubpage

#390 robot Update chart to branch gh-pages
  index.yaml
  multus-underlay-0.1.6.tgz
Labels: pr/release/robot_update_githubpage

#392 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  contour-9.1.6.tgz
  coredns-metrics-0.1.0.tgz
  f5networks-0.2.0.tgz
  falco-2.0.17.tgz
  falco-event-generator-0.1.1.tgz
  falco-exporter-0.8.2.tgz
  index.yaml
  ingress-nginx-4.2.1.tgz
  metallb-0.13.7.tgz
  metrics-server-3.8.3.tgz
  multus-underlay-0.1.6.tgz
  nmstate-0.74.0.tgz
  node-problem-detector-2.3.1.tgz
  spiderdoctor-0.2.7.tgz
  spiderpool-0.3.5.tgz
  vpa-1.5.0.tgz
Labels: pr/release/robot_update_githubpage

#405 modify resource requests
  charts/f5networks/f5networks/charts/f5-bigip-ctlr/crds/f5-bigip-ctlr-customresourcedefinitions.yml
  charts/f5networks/f5networks/charts/f5-bigip-ctlr/values.yaml
  charts/f5networks/f5networks/charts/f5-ipam-controller/Chart.yaml
  charts/f5networks/f5networks/charts/f5-ipam-controller/templates/f5-ipam-controller-deploy.yaml
  charts/f5networks/f5networks/charts/f5-ipam-controller/values.yaml
  charts/f5networks/update.sh
  charts/falco-event-generator/custom.sh
  charts/falco-event-generator/falco-event-generator/values.yaml
  charts/falco-event-generator/skip-check.yaml
  charts/falco-exporter/falco-exporter/values.yaml
  charts/falco-exporter/parent/values.yaml
  charts/falco-exporter/skip-check.yaml
  charts/falco/falco/values.yaml
  charts/falco/parent/values.yaml
Labels: documentation, enhancement

#436 robot Update chart to branch gh-pages
  index.yaml
  metallb-0.13.7.tgz
Labels: pr/release/robot_update_githubpage

#435 robot Update chart to branch gh-pages
  index.yaml
  nmstate-0.74.0.tgz
Labels: pr/release/robot_update_githubpage

#434 robot Update chart to branch gh-pages
  index.yaml
  multus-underlay-0.2.1.tgz
Labels: pr/release/robot_update_githubpage

#316 modify spiderpool components charts resources
  charts/spiderpool/config
  charts/spiderpool/custom.sh
  charts/spiderpool/spiderpool/Chart.yaml
  charts/spiderpool/spiderpool/README.md
  charts/spiderpool/spiderpool/charts/spiderpool/Chart.yaml
  charts/spiderpool/spiderpool/charts/spiderpool/README.md
  charts/spiderpool/spiderpool/charts/spiderpool/templates/configmap.yaml
  charts/spiderpool/spiderpool/charts/spiderpool/values.yaml
  charts/spiderpool/spiderpool/values.yaml
Labels: enhancement, robot-upgrade

#445 robot Update chart to branch gh-pages
  index.yaml
  spiderpool-0.3.6.tgz
Labels: pr/release/robot_update_githubpage

#455 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  contour-9.1.6.tgz
  coredns-metrics-0.1.0.tgz
  f5networks-0.2.0.tgz
  falco-2.0.17.tgz
  falco-event-generator-0.1.1.tgz
  falco-exporter-0.8.2.tgz
  index.yaml
  ingress-nginx-4.2.1.tgz
  metallb-0.13.7.tgz
  metrics-server-3.8.3.tgz
  multus-underlay-0.2.1.tgz
  nmstate-0.74.0.tgz
  node-problem-detector-2.3.1.tgz
  spiderdoctor-0.3.0.tgz
  spiderpool-0.3.6.tgz
  vpa-1.5.0.tgz
Labels: pr/release/robot_update_githubpage

#472 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  contour-9.1.6.tgz
  coredns-metrics-0.1.0.tgz
  f5networks-0.2.0.tgz
  falco-2.0.17.tgz
  falco-event-generator-0.1.1.tgz
  falco-exporter-0.8.2.tgz
  index.yaml
  ingress-nginx-4.2.1.tgz
  metallb-0.13.7.tgz
  metrics-server-3.8.3.tgz
  multus-underlay-0.2.1.tgz
  nmstate-0.74.0.tgz
  node-problem-detector-2.3.1.tgz
  spiderdoctor-0.3.0.tgz
  spiderpool-0.3.6.tgz
  vpa-1.5.0.tgz
Labels: pr/release/robot_update_githubpage
