Repository DaoCloud/dce-charts-repackage, pull requests merged in 2023-01, with the labels that each got.

#487 robot Update chart to branch gh-pages
  index.yaml
  multus-underlay-0.2.1.tgz
Labels: pr/release/robot_update_githubpage

#490 robot Update chart to branch gh-pages
  index.yaml
  velero-3.0.0.tgz
Labels: pr/release/robot_update_githubpage

#488 fix: unable to find secret f5-bigip-ctlr-login
  .github/workflows/ci.yaml
  charts/f5networks/config
  charts/f5networks/f5networks/charts/f5-bigip-ctlr/Chart.yaml
  charts/f5networks/f5networks/charts/f5-bigip-ctlr/crds/f5-bigip-ctlr-customresourcedefinitions.yml
  charts/f5networks/f5networks/charts/f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
  charts/f5networks/f5networks/charts/f5-ipam-controller/Chart.yaml
  charts/f5networks/f5networks/charts/f5-ipam-controller/README.md
  charts/f5networks/f5networks/charts/f5-ipam-controller/templates/f5-ipam-controller-deploy.yaml
  charts/f5networks/f5networks/charts/f5-ipam-controller/values.yaml
  charts/f5networks/f5networks/templates/cis-secret.yaml
  charts/f5networks/parent/templates/cis-secret.yaml
  charts/f5networks/update.sh
  scripts/generateChart.sh
  test/f5networks/install.sh
Labels: kind/bug

#500 Robot Upgrade: cert-manager chart upgrade from 1.9.1 to v1.10.2
  charts/cert-manager/cert-manager/charts/cert-manager/Chart.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/README.md
  charts/cert-manager/cert-manager/charts/cert-manager/templates/_helpers.tpl
  charts/cert-manager/cert-manager/charts/cert-manager/templates/cainjector-deployment.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/crds.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/deployment.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/networkpolicy-egress.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/networkpolicy-webhooks.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/servicemonitor.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/startupapicheck-job.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/templates/webhook-deployment.yaml
  charts/cert-manager/cert-manager/charts/cert-manager/values.yaml
  charts/cert-manager/cert-manager/values.yaml
  charts/cert-manager/config
Labels: robot-upgrade//cert-manager

#502 robot Update chart to branch gh-pages
  cert-manager-1.9.1.tgz
  index.yaml
Labels: pr/release/robot_update_githubpage
